spring:
  application:
    name: awss3-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
aws:
  s3:
    bucket: media-bucket
  cloudWatch:
    log:
      group:
        name: media-log-group
      stream:
        name: media-log-stream
  dynamoDB:
    table-name: file_metadata
  sns:
    topic-name: file-topic
  sqs:
    queue-name: file-queue
  region: us-east-1
  access-key: LKIAQAAAAAAABZEXGME3
  secret-key: eNBA3P5SND7gTa+gGdLbVS6VnRPy/24dQx9DW4dX
  endpoint: http://localhost:4566
